import { sql } from 'drizzle-orm';
import { getDb } from './drizzle';

interface BackupData {
  exportedAt: string;
  version: string;
  data: Record<string, unknown>;
}

// Construye una consulta "SELECT * FROM <table>" con filtro por tenant cuando la
// tabla tiene columna tenant_id. El tenantId se pasa como parámetro ligado para
// evitar inyección y el WHERE se antepone al ORDER BY.
function tq(tenantId: string, table: string, orderBy = ''): string {
  const where = `tenant_id = ${sql.param(tenantId)}`;
  return `SELECT * FROM ${table} WHERE ${where}${orderBy ? ` ORDER BY ${orderBy}` : ''}`;
}

// Tablas sin columna tenant_id: su alcance coincide con los datos del tenant
// cuyo backup se genera (singletons/globales, o ligadas por FK a una tabla
// madre con tenant_id). Se incluyen sin filtro; es una limitación conocida en
// despliegue multi-tenant (ver docs/GAP_LIST.md).
function tqPlain(table: string, orderBy = ''): string {
  return `SELECT * FROM ${table}${orderBy ? ` ORDER BY ${orderBy}` : ''}`;
}

export async function backupAll(tenantId: string): Promise<BackupData> {
  const db = getDb();

  const [
    categories, products, tables, orders, sales, employees, accessLogs,
    stockLog, cancelledOrders, offers, settings,
    deliveryRunners, deliveryOrders, deliveryTracking,
    mealMenus, mealMenuCourses, mealMenuCourseItems, mealMenuSchedules,
    waitlist, clockinLogs, clockinCorrections, timeOffRequests,
    employeeShifts, shiftObjectives,
    suppliers, supplierCatalog, purchaseOrders, purchaseOrderLines,
    autoOrderSettings, supplierPriceHistory,
    buffetConfig, buffetSessions, buffetRounds, buffetWaste,
    combos, combosSlots, combosSlotItems, combosItems,
    qrOrders, qrCalls,
    reservations, reservationRecurring,
    deliveryZones,
    recipes, recipeIngredients, modifierRecipes, modifierRecipeIngredients,
    productions, productionIngredients,
    albaranes, albaranLines, productBatches,
    closures,
    webhookEvents,
    verifactuRegistros, paymentLogs, fiskalyConfig,
    modifierGroups, modifierOptions, productModifiers,
    productStock, productPriceRules,
    employeeTurns,
    gestoriaSettings, gestoriaDocuments, gestoriaDocumentLines,
    gestoriaPayrolls, gestoriaTaxModels, gestoriaAuthorization,
    kdsPairings, kdsAuditLog,
    backups, tenants,
  ] = await Promise.all([
    db.execute(sql`${tq(tenantId, 'categories')}`),
    db.execute(sql`${tq(tenantId, 'products')}`),
    db.execute(sql`${tq(tenantId, 'tables')}`),
    db.execute(sql`${tq(tenantId, 'orders')}`),
    db.execute(sql`${tq(tenantId, 'sales')}`),
    db.execute(sql`${tq(tenantId, 'employees')}`),
    db.execute(sql`${tq(tenantId, 'access_logs', 'id')}`),
    db.execute(sql`${tq(tenantId, 'stock_log', 'id')}`),
    db.execute(sql`${tq(tenantId, 'cancelled_orders', 'id')}`),
    db.execute(sql`${tq(tenantId, 'offers')}`),
    db.execute(sql`${tq(tenantId, 'settings')}`),
    db.execute(sql`${tq(tenantId, 'delivery_runners')}`),
    db.execute(sql`${tq(tenantId, 'delivery_orders')}`),
    db.execute(sql`${tq(tenantId, 'delivery_tracking', 'id')}`),
    db.execute(sql`${tq(tenantId, 'meal_menus')}`),
    db.execute(sql`${tq(tenantId, 'meal_menu_courses', 'id')}`),
    db.execute(sql`${tq(tenantId, 'meal_menu_course_items', 'id')}`),
    db.execute(sql`${tq(tenantId, 'meal_menu_schedules', 'id')}`),
    db.execute(sql`${tq(tenantId, 'waitlist', 'position')}`),
    db.execute(sql`${tq(tenantId, 'clockin_logs', 'id')}`),
    db.execute(sql`${tqPlain('clockin_corrections', 'id')}`),
    db.execute(sql`${tq(tenantId, 'time_off_requests', 'created_at')}`),
    db.execute(sql`${tq(tenantId, 'employee_shifts', 'date')}`),
    db.execute(sql`${tqPlain('shift_objectives', 'id')}`),
    db.execute(sql`${tq(tenantId, 'suppliers', 'name')}`),
    db.execute(sql`${tq(tenantId, 'supplier_catalog', 'supplier_id, product_id')}`),
    db.execute(sql`${tq(tenantId, 'purchase_orders', 'created_at DESC')}`),
    db.execute(sql`${tq(tenantId, 'purchase_order_lines', 'id')}`),
    db.execute(sql`${tqPlain('auto_order_settings')}`),
    db.execute(sql`${tqPlain('supplier_price_history', 'created_at DESC')}`),
    db.execute(sql`${tq(tenantId, 'buffet_config')}`),
    db.execute(sql`${tq(tenantId, 'buffet_sessions', 'started_at DESC')}`),
    db.execute(sql`${tqPlain('buffet_rounds', 'round_number')}`),
    db.execute(sql`${tqPlain('buffet_waste', 'created_at')}`),
    db.execute(sql`${tq(tenantId, 'combos')}`),
    db.execute(sql`${tq(tenantId, 'combo_slots', 'id')}`),
    db.execute(sql`${tq(tenantId, 'combo_slot_items', 'id')}`),
    db.execute(sql`${tq(tenantId, 'combo_items', 'id')}`),
    db.execute(sql`${tq(tenantId, 'qr_orders', 'id')}`),
    db.execute(sql`${tq(tenantId, 'qr_calls', 'id')}`),
    db.execute(sql`${tq(tenantId, 'reservations', 'created_at DESC')}`),
    db.execute(sql`${tq(tenantId, 'reservation_recurring', 'id')}`),
    db.execute(sql`${tq(tenantId, 'delivery_zones', 'name')}`),
    db.execute(sql`${tq(tenantId, 'recipes', 'id')}`),
    db.execute(sql`${tq(tenantId, 'recipe_ingredients', 'id')}`),
    db.execute(sql`${tqPlain('modifier_recipes', 'id')}`),
    db.execute(sql`${tq(tenantId, 'modifier_recipe_ingredients', 'id')}`),
    db.execute(sql`${tq(tenantId, 'productions', 'id')}`),
    db.execute(sql`${tq(tenantId, 'production_ingredients', 'id')}`),
    db.execute(sql`${tq(tenantId, 'albaranes', 'id')}`),
    db.execute(sql`${tq(tenantId, 'albaran_lines', 'id')}`),
    db.execute(sql`${tqPlain('product_batches', 'id')}`),
    db.execute(sql`${tq(tenantId, 'closures', 'id')}`),
    db.execute(sql`${tq(tenantId, 'webhook_events', 'id')}`),
    db.execute(sql`${tq(tenantId, 'verifactu_registros', 'id')}`),
    db.execute(sql`${tq(tenantId, 'payment_logs', 'id')}`),
    db.execute(sql`${tqPlain('fiskaly_config')}`),
    db.execute(sql`${tq(tenantId, 'modifier_groups', 'id')}`),
    db.execute(sql`${tq(tenantId, 'modifier_options', 'id')}`),
    db.execute(sql`${tq(tenantId, 'product_modifiers', 'id')}`),
    db.execute(sql`${tq(tenantId, 'product_stock', 'id')}`),
    db.execute(sql`${tq(tenantId, 'product_price_rules', 'id')}`),
    db.execute(sql`${tq(tenantId, 'employee_turns', 'id')}`),
    db.execute(sql`${tq(tenantId, 'employees', 'id')}`),
    db.execute(sql`${tqPlain('gestoria_settings')}`),
    db.execute(sql`${tq(tenantId, 'gestoria_documents', 'id')}`),
    db.execute(sql`${tq(tenantId, 'gestoria_document_lines', 'id')}`),
    db.execute(sql`${tq(tenantId, 'gestoria_payrolls', 'id')}`),
    db.execute(sql`${tq(tenantId, 'gestoria_tax_models', 'id')}`),
    db.execute(sql`SELECT * FROM gestoria_authorization WHERE tenant_id = ${sql.param(tenantId)} AND id = 1`),
    db.execute(sql`${tq(tenantId, 'kds_pairings', 'id')}`),
    db.execute(sql`${tq(tenantId, 'kds_audit_log', 'id')}`),
    db.execute(sql`SELECT * FROM backups WHERE tenant_id = ${sql.param(tenantId)} ORDER BY created_at DESC LIMIT 10`),
    db.execute(sql`SELECT * FROM tenants WHERE id = ${sql.param(tenantId)}`),
  ]);

  const extract = (r: { rows: unknown[] }) => r.rows;

  return {
    exportedAt: new Date().toISOString(),
    version: '3.0',
    data: {
      categories: extract(categories), products: extract(products),
      tables: extract(tables), orders: extract(orders),
      sales: extract(sales), employees: extract(employees),
      accessLogs: extract(accessLogs),
      stockLog: extract(stockLog), cancelledOrders: extract(cancelledOrders),
      offers: extract(offers), settings: extract(settings),
      backups: extract(backups),
      deliveryRunners: extract(deliveryRunners),
      deliveryOrders: extract(deliveryOrders),
      deliveryTracking: extract(deliveryTracking),
      mealMenus: extract(mealMenus),
      mealMenuCourses: extract(mealMenuCourses),
      mealMenuCourseItems: extract(mealMenuCourseItems),
      mealMenuSchedules: extract(mealMenuSchedules),
      waitlist: extract(waitlist),
      qrOrders: extract(qrOrders), qrCalls: extract(qrCalls),
      reservations: extract(reservations),
      reservationRecurring: extract(reservationRecurring),
      deliveryZones: extract(deliveryZones),
      produtosRecipes: extract(recipes),
      recipeIngredients: extract(recipeIngredients),
      modifierRecipes: extract(modifierRecipes),
      modifierRecipeIngredients: extract(modifierRecipeIngredients),
      productions: extract(productions),
      productionIngredients: extract(productionIngredients),
      suppliers: extract(suppliers),
      supplierCatalog: extract(supplierCatalog),
      purchaseOrders: extract(purchaseOrders),
      purchaseOrderLines: extract(purchaseOrderLines),
      autoOrderSettings: extract(autoOrderSettings),
      supplierPriceHistory: extract(supplierPriceHistory),
      buffetConfig: extract(buffetConfig),
      buffetSessions: extract(buffetSessions),
      buffetRounds: extract(buffetRounds),
      buffetWaste: extract(buffetWaste),
      combos: extract(combos),
      combosSlots: extract(combosSlots),
      combosSlotItems: extract(combosSlotItems),
      combosItems: extract(combosItems),
      albaranes: extract(albaranes),
      albaranLines: extract(albaranLines),
      productBatches: extract(productBatches),
      closures: extract(closures),
      webhookEvents: extract(webhookEvents),
      verifactuRegistros: extract(verifactuRegistros),
      paymentLogs: extract(paymentLogs),
      fiskalyConfig: extract(fiskalyConfig),
      modifierGroups: extract(modifierGroups),
      modifierOptions: extract(modifierOptions),
      productModifiers: extract(productModifiers),
      productStock: extract(productStock),
      productPriceRules: extract(productPriceRules),
      employeeTurns: extract(employeeTurns),
      clockinLogs: extract(clockinLogs),
      clockinCorrections: extract(clockinCorrections),
      timeOffRequests: extract(timeOffRequests),
      employeeShifts: extract(employeeShifts),
      shiftObjectives: extract(shiftObjectives),
      gestoriaSettings: extract(gestoriaSettings),
      gestoriaDocuments: extract(gestoriaDocuments),
      gestoriaDocumentLines: extract(gestoriaDocumentLines),
      gestoriaPayrolls: extract(gestoriaPayrolls),
      gestoriaTaxModels: extract(gestoriaTaxModels),
      gestoriaAuthorization: extract(gestoriaAuthorization),
      kdsPairings: extract(kdsPairings),
      kdsAuditLog: extract(kdsAuditLog),
      tenants: extract(tenants),
    },
  };
}
