import { sql } from 'drizzle-orm';
import { getDb } from './drizzle';

interface BackupData {
  exportedAt: string;
  version: string;
  data: Record<string, unknown>;
}

export async function backupAll(): Promise<BackupData> {
  const db = getDb();

  const [
    categories, products, tables, orders, sales, employees, accessLogs,
    stockLog, cancelledOrders, offers, settings, backups,
    deliveryRunners, deliveryOrders, deliveryTracking,
    mealMenus, mealMenuCourses, mealMenuCourseItems, mealMenuSchedules,
    waitlist, clockinLogs, clockinCorrections, timeOffRequests,
    employeeShifts, shiftObjectives,
    suppliers, supplierCatalog, purchaseOrders, purchaseOrderLines,
    autoOrderSettings, supplierPriceHistory,
    buffetConfig, buffetSessions, buffetRounds, buffetWaste,
    combos, combosSlots, combosSlotItems, combosItems,
    qrOrders, qrCalls,
    reservations, reservationRecurring,
    deliveryZones,
    recipes, recipeIngredients, modifierRecipes, modifierRecipeIngredients,
    productions, productionIngredients,
    albaranes, albaranLines, productBatches,
    closures,
    webhookEvents,
    verifactuRegistros, paymentLogs, fiskalyConfig,
    modifierGroups, modifierOptions, productModifiers,
    productStock, productPriceRules,
    employeeTurns,
    gestoriaSettings, gestoriaDocuments, gestoriaDocumentLines,
    gestoriaPayrolls, gestoriaTaxModels, gestoriaAuthorization,
    kdsPairings, kdsAuditLog,
    tenants,
  ] = await Promise.all([
    db.execute(sql`SELECT * FROM categories`),
    db.execute(sql`SELECT * FROM products`),
    db.execute(sql`SELECT * FROM tables`),
    db.execute(sql`SELECT * FROM orders`),
    db.execute(sql`SELECT * FROM sales`),
    db.execute(sql`SELECT * FROM employees`),
    db.execute(sql`SELECT * FROM access_logs ORDER BY id`),
    db.execute(sql`SELECT * FROM stock_log ORDER BY id`),
    db.execute(sql`SELECT * FROM cancelled_orders ORDER BY id`),
    db.execute(sql`SELECT * FROM offers`),
    db.execute(sql`SELECT * FROM settings`),
    db.execute(sql`SELECT * FROM backups ORDER BY created_at DESC LIMIT 10`),
    db.execute(sql`SELECT * FROM delivery_runners`),
    db.execute(sql`SELECT * FROM delivery_orders`),
    db.execute(sql`SELECT * FROM delivery_tracking ORDER BY id`),
    db.execute(sql`SELECT * FROM meal_menus`),
    db.execute(sql`SELECT * FROM meal_menu_courses ORDER BY id`),
    db.execute(sql`SELECT * FROM meal_menu_course_items ORDER BY id`),
    db.execute(sql`SELECT * FROM meal_menu_schedules ORDER BY id`),
    db.execute(sql`SELECT * FROM waitlist ORDER BY position`),
    db.execute(sql`SELECT * FROM clockin_logs ORDER BY id`),
    db.execute(sql`SELECT * FROM clockin_corrections ORDER BY id`),
    db.execute(sql`SELECT * FROM time_off_requests ORDER BY created_at`),
    db.execute(sql`SELECT * FROM employee_shifts ORDER BY date`),
    db.execute(sql`SELECT * FROM shift_objectives ORDER BY id`),
    db.execute(sql`SELECT * FROM suppliers ORDER BY name`),
    db.execute(sql`SELECT * FROM supplier_catalog ORDER BY supplier_id, product_id`),
    db.execute(sql`SELECT * FROM purchase_orders ORDER BY created_at DESC`),
    db.execute(sql`SELECT * FROM purchase_order_lines ORDER BY id`),
    db.execute(sql`SELECT * FROM auto_order_settings`),
    db.execute(sql`SELECT * FROM supplier_price_history ORDER BY created_at DESC`),
    db.execute(sql`SELECT * FROM buffet_config`),
    db.execute(sql`SELECT * FROM buffet_sessions ORDER BY started_at DESC`),
    db.execute(sql`SELECT * FROM buffet_rounds ORDER BY round_number`),
    db.execute(sql`SELECT * FROM buffet_waste ORDER BY created_at`),
    db.execute(sql`SELECT * FROM combos`),
    db.execute(sql`SELECT * FROM combo_slots ORDER BY id`),
    db.execute(sql`SELECT * FROM combo_slot_items ORDER BY id`),
    db.execute(sql`SELECT * FROM combo_items ORDER BY id`),
    db.execute(sql`SELECT * FROM qr_orders ORDER BY id`),
    db.execute(sql`SELECT * FROM qr_calls ORDER BY id`),
    db.execute(sql`SELECT * FROM reservations ORDER BY created_at DESC`),
    db.execute(sql`SELECT * FROM reservation_recurring ORDER BY id`),
    db.execute(sql`SELECT * FROM delivery_zones ORDER BY name`),
    db.execute(sql`SELECT * FROM recipes ORDER BY id`),
    db.execute(sql`SELECT * FROM recipe_ingredients ORDER BY id`),
    db.execute(sql`SELECT * FROM modifier_recipes ORDER BY id`),
    db.execute(sql`SELECT * FROM modifier_recipe_ingredients ORDER BY id`),
    db.execute(sql`SELECT * FROM productions ORDER BY id`),
    db.execute(sql`SELECT * FROM production_ingredients ORDER BY id`),
    db.execute(sql`SELECT * FROM albaranes ORDER BY id`),
    db.execute(sql`SELECT * FROM albaran_lines ORDER BY id`),
    db.execute(sql`SELECT * FROM product_batches ORDER BY id`),
    db.execute(sql`SELECT * FROM closures ORDER BY id`),
    db.execute(sql`SELECT * FROM webhook_events ORDER BY id`),
    db.execute(sql`SELECT * FROM verifactu_registros ORDER BY id`),
    db.execute(sql`SELECT * FROM payment_logs ORDER BY id`),
    db.execute(sql`SELECT * FROM fiskaly_config`),
    db.execute(sql`SELECT * FROM modifier_groups ORDER BY id`),
    db.execute(sql`SELECT * FROM modifier_options ORDER BY id`),
    db.execute(sql`SELECT * FROM product_modifiers ORDER BY id`),
    db.execute(sql`SELECT * FROM product_stock ORDER BY id`),
    db.execute(sql`SELECT * FROM product_price_rules ORDER BY id`),
    db.execute(sql`SELECT * FROM employee_turns ORDER BY id`),
    db.execute(sql`SELECT * FROM employees ORDER BY id`),
    db.execute(sql`SELECT * FROM gestoria_settings`),
    db.execute(sql`SELECT * FROM gestoria_documents ORDER BY id`),
    db.execute(sql`SELECT * FROM gestoria_document_lines ORDER BY id`),
    db.execute(sql`SELECT * FROM gestoria_payrolls ORDER BY id`),
    db.execute(sql`SELECT * FROM gestoria_tax_models ORDER BY id`),
    db.execute(sql`SELECT * FROM gestoria_authorization WHERE id = 1`),
    db.execute(sql`SELECT * FROM kds_pairings ORDER BY id`),
    db.execute(sql`SELECT * FROM kds_audit_log ORDER BY id`),
    db.execute(sql`SELECT * FROM tenants WHERE id = 'default'`),
  ]);

  const extract = (r: { rows: unknown[] }) => r.rows;

  return {
    exportedAt: new Date().toISOString(),
    version: '3.0',
    data: {
      categories: extract(categories), products: extract(products),
      tables: extract(tables), orders: extract(orders),
      sales: extract(sales), employees: extract(employees),
      accessLogs: extract(accessLogs),
      stockLog: extract(stockLog), cancelledOrders: extract(cancelledOrders),
      offers: extract(offers), settings: extract(settings),
      backups: extract(backups),
      deliveryRunners: extract(deliveryRunners),
      deliveryOrders: extract(deliveryOrders),
      deliveryTracking: extract(deliveryTracking),
      mealMenus: extract(mealMenus),
      mealMenuCourses: extract(mealMenuCourses),
      mealMenuCourseItems: extract(mealMenuCourseItems),
      mealMenuSchedules: extract(mealMenuSchedules),
      waitlist: extract(waitlist),
      qrOrders: extract(qrOrders), qrCalls: extract(qrCalls),
      reservations: extract(reservations),
      reservationRecurring: extract(reservationRecurring),
      deliveryZones: extract(deliveryZones),
      produtosRecipes: extract(recipes),
      recipeIngredients: extract(recipeIngredients),
      modifierRecipes: extract(modifierRecipes),
      modifierRecipeIngredients: extract(modifierRecipeIngredients),
      productions: extract(productions),
      productionIngredients: extract(productionIngredients),
      suppliers: extract(suppliers),
      supplierCatalog: extract(supplierCatalog),
      purchaseOrders: extract(purchaseOrders),
      purchaseOrderLines: extract(purchaseOrderLines),
      autoOrderSettings: extract(autoOrderSettings),
      supplierPriceHistory: extract(supplierPriceHistory),
      buffetConfig: extract(buffetConfig),
      buffetSessions: extract(buffetSessions),
      buffetRounds: extract(buffetRounds),
      buffetWaste: extract(buffetWaste),
      combos: extract(combos),
      combosSlots: extract(combosSlots),
      combosSlotItems: extract(combosSlotItems),
      combosItems: extract(combosItems),
      albaranes: extract(albaranes),
      albaranLines: extract(albaranLines),
      productBatches: extract(productBatches),
      closures: extract(closures),
      webhookEvents: extract(webhookEvents),
      verifactuRegistros: extract(verifactuRegistros),
      paymentLogs: extract(paymentLogs),
      fiskalyConfig: extract(fiskalyConfig),
      modifierGroups: extract(modifierGroups),
      modifierOptions: extract(modifierOptions),
      productModifiers: extract(productModifiers),
      productStock: extract(productStock),
      productPriceRules: extract(productPriceRules),
      employeeTurns: extract(employeeTurns),
      clockinLogs: extract(clockinLogs),
      clockinCorrections: extract(clockinCorrections),
      timeOffRequests: extract(timeOffRequests),
      employeeShifts: extract(employeeShifts),
      shiftObjectives: extract(shiftObjectives),
      gestoriaSettings: extract(gestoriaSettings),
      gestoriaDocuments: extract(gestoriaDocuments),
      gestoriaDocumentLines: extract(gestoriaDocumentLines),
      gestoriaPayrolls: extract(gestoriaPayrolls),
      gestoriaTaxModels: extract(gestoriaTaxModels),
      gestoriaAuthorization: extract(gestoriaAuthorization),
      kdsPairings: extract(kdsPairings),
      kdsAuditLog: extract(kdsAuditLog),
      tenants: extract(tenants),
    },
  };
}
